version: "2.2"

services:
  keycloak:
    build: keycloak
    image: ci-stack-keycloak
    ports:
      - 8280:8080
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Keycloak"
      - com.github.joostvdg.description="Single Sign On facility"
      - com.github.joostvdg.webPath=/
      - com.github.joostvdg.webPort=8280
    links:
      - postgres
    depends_on:
      - postgres
      - ldap
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=DEBUG
      - DB_VENDOR=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
    command: -b 0.0.0.0 -Dkeycloak.import=/tmp/realms/ci-realm-export.json
  
  docs:
    build: docs
    image: ci-stack-docs
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Docs"
      - com.github.joostvdg.description="User documentation"
      - com.github.joostvdg.webPath=/
      - com.github.joostvdg.webPort=8281
    ports:
      - 8281:80

  jenkins:
    build: jenkins
    image: ci-stack-jenkins
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Jenkins Master"
      - com.github.joostvdg.description="Jenkins - CI/Build server"
      - com.github.joostvdg.webPath=/jenkins
      - com.github.joostvdg.webPort=8282
    environment:
      - HOSTNAME=${JENKINS_HOSTNAME:-localhost}
      - EXTERNAL_PORT=${JENKINS_EXTERNAL_PORT:-8282}
      - CONTEXT_ROOT=${JENKINS_CONTEXT_ROOT:-/jenkins}
      - KEYCLOAK_HOSTNAME=${hostname:-localhost}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT:-8280}
      - KEYCLOAK_HOSTNAME_SUFFIX=${KEYCLOAK_HOSTNAME_SUFFIX:-.solon.prd}
      - KEYCLOAK_HOSTNAME_LOWERCASE=${KEYCLOAK_HOSTNAME_LOWERCASE:-true}
      - SONAR_HOSTNAME=${SONAR_HOSTNAME:-sonar}
      - NEXUS_HOSTNAME=${NEXUS_HOSTNAME:-nexus}
      - THEME_CSS=http://q-nexus-3.nl.eu.abnamro.com:8082/repository/npm-3rd-party-raw-hosting/cicdsandbox/jenkins-material-theme.css
    ports:
      - 8282:8080
      - 50000:50000
    volumes: ["jenkins_data:/var/jenkins_home"]

  jenkins-slave:
    image: vfarcic/jenkins-swarm-agent:18.02.12-10
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Jenkins Slave"
      - com.github.joostvdg.description="Slave with link to docker socket"
    depends_on:
      - jenkins
    environment:
      - COMMAND_OPTIONS=-master http://jenkins:8080/jenkins -labels 'docker' -executors 2
    volumes: ["jenkins_slave_workspace:/workspace", "/var/run/docker.sock:/var/run/docker.sock"]

  sonar:
    image: ci-stack-sonar
    build: sonar
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="SonarQube"
      - com.github.joostvdg.webPath=/sonar
      - com.github.joostvdg.webPort=8289
      - com.github.joostvdg.description="SonarQube - for software quality scan"
    ports:
      - 8289:9000    
    volumes: ["sonar_data:/opt/sonarqube/data"]
    command: -Dsonar.web.context=/sonar

  postgres:
    image: postgres:9.6.7
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Postgres"
      - com.github.joostvdg.description="Database for Keycloak"
    ports:    
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin4:
    image: chorss/docker-pgadmin4
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="PGAdmin 4"
      - com.github.joostvdg.description="Web admin console for postgres"
      - com.github.joostvdg.webPath=/
      - com.github.joostvdg.webPort=5050
    depends_on:
      - postgres
    ports:
      - 5050:5050
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    volumes:
      - pgadmin_data:/data

## Artifactory
# Default user: admin:password
  artifactory:                               
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Artifactory OSS"
      - com.github.joostvdg.description="Binary repository for development"
      - com.github.joostvdg.webPath=/artifactory
      - com.github.joostvdg.webPort=8285
    ports:
      - 8285:8081
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    volumes: ["artifactory_data:/var/opt/jfrog/artifactory"]


  # Default Nexus 3 images is poor for mounting data
  # https://github.com/cavemandaveman/nexus
  # nexus:                               
  #   image: cavemandaveman/nexus:3.9.0-01
  #   labels:
  #     - com.github.joostvdg.namespace=cidc
  #     - com.github.joostvdg.name="Nexus 3"
  #     - com.github.joostvdg.description="Binary repository"
  #     - com.github.joostvdg.webPath=/nexus
  #     - com.github.joostvdg.webPort=8284
  #   ports:
  #     - 8284:8081
  #   volumes: ["nexus_data:/nexus-data"]

  portainer:
    image: portainer/portainer
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Portainer"
      - com.github.joostvdg.description="Admin console for Docker"
      - com.github.joostvdg.webPath=/
      - com.github.joostvdg.webPort=9000
    ports:
      - 9000:9000
    volumes: ["/var/run/docker.sock:/var/run/docker.sock","portainer_data:/data portainer/portainer"]

  ldap: 
    image: ci-stack-opendj 
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="OpenDJ"
      - com.github.joostvdg.description="LDAP server for user management"
    build: ldap 
    ports: 
      - 11389:1389 
      - 11636:1636 
      - 14444:4444

## Splunk
# https://hub.docker.com/r/splunk/splunk/
# admin / changeme
# Jenkins token: 806b2310-ced6-4693-b3e4-f81bd17f41e8
# we need to add "--answer-yes" due to upgrade stuff: https://github.com/splunk/docker-splunk/issues/21
  splunk:
    image: q-nexus-3.nl.eu.abnamro.com:18445/splunk/splunk:7.0.0-monitor
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Splunk"
      - com.github.joostvdg.description="DevOps logging/dashboarding tool"
      - com.github.joostvdg.webPath=/
      - com.github.joostvdg.webPort=8287
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_USER=root
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=tcp 1514
    depends_on:
      - registry
    ports: 
      - 8287:8000 
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    volumes: ["opt-splunk-etc:/opt/splunk/etc","opt-splunk-var:/opt/splunk/var", "/var/run/docker.sock:/var/run/docker.sock"]

  service-listing: 
    image: abnamrocoesd/cicd-sandbox-util:latest
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="CIDC Service Listing"
      - com.github.joostvdg.description="The container of this page"
    ports:
      - 7777:7777
    command: cicd-util -action serve -labelPrefix "com.github.joostvdg." -namespace "cidc"
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]

## Docker Registry
# https://docs.docker.com/registry/deploying
  registry: 
    image: registry:2
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Docker Registry"
      - com.github.joostvdg.description="Docker Registry by Docker"
    ports: 
      - 5000:5000

## Docker Registry UI
# https://hub.docker.com/r/konradkleine/docker-registry-frontend/
  registry-ui: 
    image: konradkleine/docker-registry-frontend:v2
    labels:
      - com.github.joostvdg.namespace=cidc
      - com.github.joostvdg.name="Docker Registry Frontend"
      - com.github.joostvdg.description="A UI for the docker registry"
      - com.github.joostvdg.webPath=/
      - com.github.joostvdg.webPort=8288
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    depends_on:
      - registry
    ports: 
      - 8288:80  

volumes:
  sonar_data:
  nexus_data:
  jenkins_data:
  jenkins_slave_workspace:
  artifactory_data:
  pgadmin_data:
  pg_data:
  portainer_data:
  opt-splunk-etc:
  opt-splunk-var:
